with import <nixpkgs> { };

with lib;

let 
    urlize = { owner, repo, ... }: "https://github.com/${owner}/${repo}";
    submodule-add = plugin: "git -c http.sslVerify=false submodule add ${urlize plugin}";
in runCommand "dist" {
    nativeBuildInputs = [ git coreutils ];
    src = ./..;
} ''
    mkdir -p $out/.plugins/pack/repositories/{start,opt}

    cp -R $src/{config,init}.vim $src/plugins $out

    cd $out
    git init

    # Plugins part
    cd .plugins/pack/repositories/start
    ${builtins.concatStringsSep "\n" (imap0 (_: submodule-add) (callPackage ../plugins {}))}
    
    cd $out

    # Header part
    echo "\" minimal setup, generated by NIX
    set nocompatible

    set packpath-=~/.vim/after
    set packpath+=~/.config/nvim/.plugins
    set packpath+=~/.vim/after

    filetype indent plugin on | syn on
    " | cat - init.vim > init.vim.tmp

    mv init.vim.tmp init.vim

    cd -
''
